/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{svelte,js,ts}'],
  darkMode: 'class',
  safelist: [
    'border-tech-dotnet',
    'text-tech-dotnet',
    'bg-tech-dotnet/10',
    'border-tech-dotnet/30',
    'border-tech-sql',
    'text-tech-sql',
    'bg-tech-sql/10',
    'border-tech-sql/30',
    'border-tech-cloud',
    'text-tech-cloud',
    'bg-tech-cloud/10',
    'border-tech-cloud/30',
    'border-tech-infra',
    'text-tech-infra',
    'bg-tech-infra/10',
    'border-tech-infra/30',
    'bg-primary/10',
    'border-primary/30',
    'text-primary',
    'bg-[#38bdf8]/10',
    'border-[#38bdf8]/30',
    'text-[#38bdf8]',
  ],
  theme: {
    extend: {
      colors: {
        'primary-fixed': '#7cf4fe',
        'surface-tint': '#5dd8e2',
        background: '#0b1326',
        'secondary-fixed-dim': '#c9beff',
        'on-primary': '#00363a',
        'on-background': '#dbe2fd',
        primary: '#7df5ff',
        'surface-container': '#171f33',
        'tech-cloud': '#06b6d4',
        'primary-container': '#5dd8e2',
        'tech-infra': '#475569',
        'on-secondary-fixed': '#1c1148',
        'secondary-container': '#483f77',
        'inverse-on-surface': '#283044',
        'on-error': '#690005',
        surface: '#0b1326',
        'on-primary-container': '#005c62',
        'tech-sql': '#3b82f6',
        error: '#ffb4ab',
        'surface-dim': '#0b1326',
        'on-tertiary-fixed': '#181c1e',
        'on-tertiary-fixed-variant': '#434749',
        'tertiary-container': '#c4c7c9',
        'surface-container-low': '#131b2e',
        'surface-container-high': '#222a3e',
        'on-secondary-fixed-variant': '#483f77',
        'on-surface': '#dbe2fd',
        'error-container': '#93000a',
        tertiary: '#e0e3e5',
        'tech-dotnet': '#10b981',
        'outline-variant': '#3d494a',
        'surface-container-highest': '#2d3449',
        'on-tertiary': '#2d3133',
        'on-secondary': '#31285e',
        'surface-bright': '#31394e',
        outline: '#3d494a',
        'inverse-primary': '#00696f',
        'on-tertiary-container': '#4f5355',
        'on-primary-fixed-variant': '#004f54',
        'on-surface-variant': '#bcc9ca',
        'on-primary-fixed': '#002022',
        'surface-container-lowest': '#060d20',
        'inverse-surface': '#dbe2fd',
        'tertiary-fixed-dim': '#c4c7c9',
        'secondary-fixed': '#e6deff',
        'on-error-container': '#ffdad6',
        'on-secondary-container': '#b8aded',
        'surface-variant': '#2d3449',
        'primary-fixed-dim': '#5dd8e2',
        secondary: '#c9beff',
        'tertiary-fixed': '#e0e3e5',
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        lg: '0.25rem',
        xl: '0.5rem',
        full: '0.75rem',
      },
      spacing: {
        'stack-lg': '32px',
        'margin-desktop': '64px',
        gutter: '24px',
        'stack-md': '16px',
        baseline: '4px',
        'stack-sm': '8px',
        'margin-mobile': '20px',
      },
      fontFamily: {
        sans: ['Archivo Narrow', 'sans-serif'],
        'headline-lg': ['Archivo Narrow'],
        'label-sm': ['Archivo Narrow'],
        'body-sm': ['Archivo Narrow'],
        'body-lg': ['Archivo Narrow'],
        'body-md': ['Archivo Narrow'],
        'headline-xl': ['Archivo Narrow'],
        'headline-lg-mobile': ['Archivo Narrow'],
        'label-caps': ['Archivo Narrow'],
        'headline-md': ['Archivo Narrow'],
        'code-snippet': ['Archivo Narrow'],
      },
      fontSize: {
        'headline-lg': ['32px', { lineHeight: '1.2', letterSpacing: '-0.01em', fontWeight: '600' }],
        'label-sm': ['11px', { lineHeight: '1', fontWeight: '500' }],
        'body-sm': ['14px', { lineHeight: '1.5', fontWeight: '400' }],
        'body-lg': ['18px', { lineHeight: '1.6', fontWeight: '500' }],
        'body-md': ['16px', { lineHeight: '1.6', fontWeight: '400' }],
        'headline-xl': ['48px', { lineHeight: '1.1', letterSpacing: '-0.02em', fontWeight: '700' }],
        'headline-lg-mobile': ['28px', { lineHeight: '1.2', fontWeight: '600' }],
        'label-caps': ['12px', { lineHeight: '1', letterSpacing: '0.1em', fontWeight: '700' }],
        'headline-md': ['24px', { lineHeight: '1.3', fontWeight: '600' }],
        'code-snippet': ['14px', { lineHeight: '1.7', fontWeight: '400' }],
      },
    },
  },
  plugins: [require('@tailwindcss/forms'), require('@tailwindcss/container-queries')],
};
